# Generated by Django 5.1 on 2025-09-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('UK Apostille', 'UK Apostille'), ('Embassy Legalisation', 'Embassy Legalisation'), ('Shuttle Services', 'Shuttle Services')], max_length=50)),
                ('document_type', models.CharField(max_length=255)),
                ('attested_as', models.CharField(choices=[('Original', 'Original'), ('True Copy', 'True Copy')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('calling_code', models.CharField(max_length=10)),
                ('contact_no', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
