# Generated by Django 5.1 on 2025-09-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='address2',
        ),
    ]
