# Generated by Django 5.2.5 on 2025-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_enquiry_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
